import { sql } from 'drizzle-orm';
import {
  boolean, check, customType, index, integer, jsonb, numeric, pgTable, primaryKey,
  text, timestamp, uniqueIndex
} from 'drizzle-orm/pg-core';

/** Untyped pgvector column: a profile's dimension is stored and enforced in application invariants. */
const vector = customType<{ data: number[]; driverData: string }>({
  dataType: () => 'vector',
  toDriver: (value) => `[${value.join(',')}]`,
  fromDriver: (value) => value.slice(1, -1).split(',').filter(Boolean).map(Number)
});
const tsvector = customType<{ data: string; driverData: string }>({ dataType: () => 'tsvector' });
const now = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const json = <T extends Record<string, unknown>>(name: string) => jsonb(name).$type<T>().notNull();

export const personas = pgTable('personas', {
  id: text('id').primaryKey(), displayName: text('display_name').notNull(), role: text('role').notNull(), createdAt: now()
});
export const permissionGrants = pgTable('permission_grants', {
  id: text('id').primaryKey(), personaId: text('persona_id').notNull().references(() => personas.id),
  accountId: text('account_id').references(() => accounts.id), sourceType: text('source_type'), canRead: boolean('can_read').notNull().default(false),
  canApprove: boolean('can_approve').notNull().default(false), sensitivePricing: boolean('sensitive_pricing').notNull().default(false), createdAt: now()
});
export const accounts = pgTable('accounts', { id: text('id').primaryKey(), name: text('name').notNull(), createdAt: now() });
export const opportunities = pgTable('opportunities', {
  id: text('id').primaryKey(), accountId: text('account_id').notNull().references(() => accounts.id), name: text('name').notNull(), restricted: boolean('restricted').notNull().default(false), createdAt: now()
});
export const contacts = pgTable('contacts', { id: text('id').primaryKey(), accountId: text('account_id').notNull().references(() => accounts.id), name: text('name').notNull(), email: text('email'), createdAt: now() });
export const documentVersions = pgTable('document_versions', {
  id: text('id').primaryKey(), externalId: text('external_id').notNull(), version: integer('version').notNull(), sourceType: text('source_type').notNull(), contentHash: text('content_hash').notNull(), content: text('content').notNull(), createdAt: now()
}, (table) => [uniqueIndex('document_versions_external_version_uq').on(table.externalId, table.version)]);
export const evidenceVersions = pgTable('evidence_versions', {
  id: text('id').primaryKey(), documentVersionId: text('document_version_id').notNull().references(() => documentVersions.id), accountId: text('account_id').notNull().references(() => accounts.id), opportunityId: text('opportunity_id').references(() => opportunities.id),
  chunkIndex: integer('chunk_index').notNull(), sourceType: text('source_type').notNull(), sensitivity: text('sensitivity').notNull(), contentHash: text('content_hash').notNull(), content: text('content').notNull(),
  embedding: vector('embedding'), embeddingProvider: text('embedding_provider'), embeddingModel: text('embedding_model'), embeddingDimension: integer('embedding_dimension'), embeddingProfile: text('embedding_profile'), embeddingVersion: text('embedding_version'), embeddingNormalization: text('embedding_normalization'), lexicalContent: tsvector('lexical_content').generatedAlwaysAs(sql`to_tsvector('english', coalesce(content, ''))`), createdAt: now()
}, (table) => [
  uniqueIndex('evidence_versions_document_chunk_uq').on(table.documentVersionId, table.chunkIndex),
  index('evidence_versions_fts_idx').using('gin', table.lexicalContent),
  check('evidence_versions_embedding_profile_ck', sql`(${table.embedding} is null) = (${table.embeddingProfile} is null) and (${table.embedding} is null or (${table.embeddingProvider} is not null and ${table.embeddingModel} is not null and ${table.embeddingDimension} > 0 and ${table.embeddingVersion} is not null and ${table.embeddingNormalization} is not null))`)
]);
export const runEvidenceManifests = pgTable('run_evidence_manifests', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), scopeHash: text('scope_hash').notNull(), policyHash: text('policy_hash').notNull(), indexProfile: text('index_profile').notNull(), createdAt: now() });
export const runEvidenceManifestEntries = pgTable('run_evidence_manifest_entries', { manifestId: text('manifest_id').notNull().references(() => runEvidenceManifests.id), evidenceVersionId: text('evidence_version_id').notNull().references(() => evidenceVersions.id), rank: integer('rank').notNull(), score: numeric('score').notNull(), contentHash: text('content_hash').notNull() }, (table) => [primaryKey({ columns: [table.manifestId, table.evidenceVersionId] })]);
export const runs = pgTable('runs', {
  id: text('id').primaryKey(), opportunityId: text('opportunity_id').notNull().references(() => opportunities.id), requestedBy: text('requested_by').notNull().references(() => personas.id), status: text('status').notNull(), generationProvider: text('generation_provider').notNull(), generationModel: text('generation_model').notNull(), version: integer('version').notNull().default(0), createdAt: now(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});
export const outboxCommands = pgTable('outbox_commands', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), type: text('type').notNull(), payload: json<Record<string, unknown>>('payload'), idempotencyKey: text('idempotency_key').notNull(), status: text('status').notNull().default('pending'), deliveryAttempts: integer('delivery_attempts').notNull().default(0), availableAt: timestamp('available_at', { withTimezone: true }).notNull().defaultNow(), claimedAt: timestamp('claimed_at', { withTimezone: true }), claimOwner: text('claim_owner'), claimToken: text('claim_token'), claimExpiresAt: timestamp('claim_expires_at', { withTimezone: true }), publishedAt: timestamp('published_at', { withTimezone: true }), consumedAt: timestamp('consumed_at', { withTimezone: true }), createdAt: now() }, (table) => [uniqueIndex('outbox_commands_idempotency_uq').on(table.idempotencyKey), index('outbox_commands_pending_idx').on(table.status, table.availableAt)]);
export const stepInvocations = pgTable('step_invocations', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), step: text('step').notNull(), owner: text('owner'), leaseToken: text('lease_token'), leaseExpiresAt: timestamp('lease_expires_at', { withTimezone: true }), heartbeatAt: timestamp('heartbeat_at', { withTimezone: true }), attempt: integer('attempt').notNull().default(1), status: text('status').notNull().default('leased'), createdAt: now(), completedAt: timestamp('completed_at', { withTimezone: true }) }, (table) => [uniqueIndex('step_invocations_run_step_attempt_uq').on(table.runId, table.step, table.attempt)]);
export const workflowCheckpoints = pgTable('workflow_checkpoints', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), step: text('step').notNull(), payload: json<Record<string, unknown>>('payload'), createdAt: now() }, (table) => [uniqueIndex('workflow_checkpoints_run_step_uq').on(table.runId, table.step)]);
export const generationAttempts = pgTable('generation_attempts', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), invocationId: text('invocation_id').references(() => stepInvocations.id), operation: text('operation').notNull(), status: text('status').notNull(), provider: text('provider').notNull(), model: text('model').notNull(), requestId: text('request_id'), responseId: text('response_id'), possibleDuplicate: boolean('possible_duplicate').notNull().default(false), inputTokens: integer('input_tokens'), outputTokens: integer('output_tokens'), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }) });
export const contextCheckpoints = pgTable('context_checkpoints', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), payload: json<Record<string, unknown>>('payload'), scopeHash: text('scope_hash').notNull(), policyHash: text('policy_hash').notNull(), evidenceHash: text('evidence_hash').notNull(), createdAt: now() });
export const specialistArtifacts = pgTable('specialist_artifacts', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), kind: text('kind').notNull(), evidenceManifestId: text('evidence_manifest_id').references(() => runEvidenceManifests.id), content: json<Record<string, unknown>>('content'), contentHash: text('content_hash').notNull(), createdAt: now() }, (table) => [uniqueIndex('specialist_artifacts_run_kind_uq').on(table.runId, table.kind)]);
export const claims = pgTable('claims', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), artifactId: text('artifact_id').references(() => specialistArtifacts.id), statement: text('statement').notNull(), confidence: text('confidence').notNull(), createdAt: now() });
export const citations = pgTable('citations', { id: text('id').primaryKey(), claimId: text('claim_id').notNull().references(() => claims.id), evidenceVersionId: text('evidence_version_id').notNull().references(() => evidenceVersions.id), locator: text('locator').notNull(), createdAt: now() }, (table) => [uniqueIndex('citations_claim_evidence_locator_uq').on(table.claimId, table.evidenceVersionId, table.locator)]);
export const approvalSubjects = pgTable('approval_subjects', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), draftVersion: integer('draft_version').notNull(), subjectHash: text('subject_hash').notNull(), payload: json<Record<string, unknown>>('payload'), policyTriggers: json<Record<string, unknown>>('policy_triggers'), createdAt: now() }, (table) => [uniqueIndex('approval_subjects_run_version_uq').on(table.runId, table.draftVersion), uniqueIndex('approval_subjects_subject_hash_uq').on(table.subjectHash)]);
export const approvalDecisions = pgTable('approval_decisions', { id: text('id').primaryKey(), approvalSubjectId: text('approval_subject_id').notNull().references(() => approvalSubjects.id), action: text('action').notNull(), actorId: text('actor_id').notNull().references(() => personas.id), rationale: text('rationale'), editedPayload: json<Record<string, unknown>>('edited_payload'), createdAt: now() }, (table) => [uniqueIndex('approval_decisions_subject_uq').on(table.approvalSubjectId)]);
export const briefs = pgTable('briefs', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), approvalSubjectId: text('approval_subject_id').references(() => approvalSubjects.id), payload: json<Record<string, unknown>>('payload'), subjectHash: text('subject_hash').notNull(), finalizedAt: timestamp('finalized_at', { withTimezone: true }), createdAt: now() }, (table) => [uniqueIndex('briefs_run_uq').on(table.runId)]);
export const traceSpans = pgTable('trace_spans', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), parentId: text('parent_id'), kind: text('kind').notNull(), status: text('status').notNull(), payload: json<Record<string, unknown>>('payload'), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), endedAt: timestamp('ended_at', { withTimezone: true }) });
export const runEvents = pgTable('run_events', { id: text('id').primaryKey(), runId: text('run_id').notNull().references(() => runs.id), sequence: integer('sequence').notNull(), type: text('type').notNull(), payload: json<Record<string, unknown>>('payload'), createdAt: now() }, (table) => [uniqueIndex('run_events_run_sequence_uq').on(table.runId, table.sequence)]);
export const auditEvents = pgTable('audit_events', { id: text('id').primaryKey(), runId: text('run_id').references(() => runs.id), actorId: text('actor_id').references(() => personas.id), type: text('type').notNull(), payload: json<Record<string, unknown>>('payload'), createdAt: now() });
